### PR TITLE
Add External Validation helper

### PR DESCRIPTION
**Pull request by nitrag**
Validating your receipt externally is a PITA currently, this adds a helper function that returns exactly what you need. 

Tested with NPM: `in-app-purchase`

### CODE REVIEW

**Comment by ashcoding** [comment]
This is to expose `getOriginalJson()`? `getSignature()` already exists.
Having a method to just return `getOriginalJson()` instead of a method that returns both Signature and Original Json aka `getReceipt()` might be better.

What do you think? Is it necessary to combine them into `getReceipt()`?

**Comment by nitrag** [comment]
For Google validation, receipt is an object 

```
{ data: "stringified purchase data", signature: "yyyy" }.
```

It was necessary to expose `originalJson` because the data has to be in the exact order it was received for valid decoding. So I killed two birds with one proxy method. Sure it might be cleaner to separate it but that's just one more thing to merge properly on the JS side.

**Comment by ashcoding** [comment]
Ah. Okay. Understood. 👍

**Comment by ashcoding** [comment]
@nitrag I'm going to have to cherry-pick this put it in another PR. Reason being that there's a need to branch out the ti.inappbilling for support prior to TiSDK 6 and for TiSDK 6 moving forward.

Hope that is okay for you?

**Comment by nitrag** [comment]
No problem, I'll keep an eye out for the change when I upgrade to 6.0.

**Comment by ashcoding** [comment]
I've updated this PR here: https://github.com/appcelerator-archive/ti.inappbilling/pull/24

**Comment by ashcoding** [comment]
Will be closing this.

**Pull request closed without merging**
